FROM node:lts-alpine AS build
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM node:lts
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production
COPY --from=build /usr/src/app/dist ./dist

COPY src/data ./src/data
COPY public ./public

EXPOSE 3000
CMD ["yarn", "start:prod"]